version: '3.0'

services:
  front:
    build: web
    image: vdemeester/exquisite-web
    ports: ["80:80"]

  back:
    build: words-java
    image: vdemeester/exquisite-words-java
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 64M

  mongo:
    image: mongo:3.3.8
